In [1]:
import pandas as pd
import numpy as np
from pandas.tseries.tools import to_datetime
import datetime
from ipykernel import kernelapp as app
from darksky import forecast

In [29]:
df = pd.read_csv('November_8_to_10.csv', low_memory=False)

In [30]:
df.isnull().sum()

Timestamp            0
LineId              16
JourneyPatternId    84
TimeFrame            0
VehicleJourneyId     0
BusOperator          0
Congestion           0
Long                 0
Lat                  0
Delay                0
BlockId              0
VehicleId            0
StopId               0
Distance             0
TravelTime           0
Weekday              0
TimeCategory         0
dtype: int64

In [3]:
df.head()

,Timestamp,LineId,JourneyPatternId,TimeFrame,VehicleJourneyId,BusOperator,Congestion,Long,Lat,Delay,BlockId,VehicleId,StopId,Distance,TravelTime,Weekday,TimeCategory
0,2012-11-08 16:18:13,331,033A1002,2012-11-08,1,SL,0,-6.129196,53.579613,43,33001,43051,3816,0.000000,0,3,16:00
1,2012-11-08 16:21:34,331,033A1002,2012-11-08,1,SL,0,-6.110108,53.579807,164,33001,43051,3818,1651.209589,201,3,16:00
2,2012-11-08 16:24:14,331,033A1002,2012-11-08,1,SL,0,-6.106793,53.580036,309,33001,43051,3819,1969.281027,361,3,16:00
3,2012-11-08 16:33:52,331,033A1002,2012-11-08,1,SL,0,-6.090593,53.533672,623,33001,43051,3833,7472.199689,939,3,16:30
4,2012-11-08 16:34:33,331,033A1002,2012-11-08,1,SL,0,-6.091514,53.530941,648,33001,43051,3834,7783.316730,980,3,16:30

In [4]:
# Read in weather data
#weather data file contains only relevant dates and first row containing the column names deleted

COLNAMES2 = ['Time_hour','Ind', 'Rain', 'Ind1', 'Temp', 'Ind2', 'Wetb', 'Dewpt', 'Vappr', 'Rhum', 'Msl']
df2 = pd.read_csv("weatherData.csv", names=COLNAMES2)

In [5]:
column_names = ['Time_hour', 'Rain', 'Temp']
df2 = df2[column_names]

In [6]:
for index, row in df2.iterrows():
    # Change each date to standard format year-month-day
    x = datetime.datetime.strptime(row[0], '%d/%m/%Y %H:%M').strftime('%Y-%m-%d %H')
    df2.set_value(index, 'Time_hour', x)

In [7]:
df2.Time_hour =  pd.to_datetime(df2.Time_hour)

In [8]:
df2 = df2.replace(r'\s+', np.nan, regex=True)
df2.Rain = df2.Rain.astype(float)
df2.Temp = df2.Temp.astype(float)

In [9]:
df['Time_hour'] = df['Timestamp'].values.astype('<M8[h]')

In [10]:
df2.head()

            Time_hour  Rain  Temp
0 2012-11-06 00:00:00   0.0   2.6
1 2012-11-06 01:00:00   0.0   2.8
2 2012-11-06 02:00:00   0.0   3.4
3 2012-11-06 03:00:00   0.0   4.6
4 2012-11-06 04:00:00   0.0   4.9

In [11]:
df.head()

,Timestamp,LineId,JourneyPatternId,TimeFrame,VehicleJourneyId,BusOperator,Congestion,Long,Lat,Delay,BlockId,VehicleId,StopId,Distance,TravelTime,Weekday,TimeCategory,Time_hour
0,2012-11-08 16:18:13,331,033A1002,2012-11-08,1,SL,0,-6.129196,53.579613,43,33001,43051,3816,0.000000,0,3,16:00,2012-11-08 16:00:00
1,2012-11-08 16:21:34,331,033A1002,2012-11-08,1,SL,0,-6.110108,53.579807,164,33001,43051,3818,1651.209589,201,3,16:00,2012-11-08 16:00:00
2,2012-11-08 16:24:14,331,033A1002,2012-11-08,1,SL,0,-6.106793,53.580036,309,33001,43051,3819,1969.281027,361,3,16:00,2012-11-08 16:00:00
3,2012-11-08 16:33:52,331,033A1002,2012-11-08,1,SL,0,-6.090593,53.533672,623,33001,43051,3833,7472.199689,939,3,16:30,2012-11-08 16:00:00
4,2012-11-08 16:34:33,331,033A1002,2012-11-08,1,SL,0,-6.091514,53.530941,648,33001,43051,3834,7783.316730,980,3,16:30,2012-11-08 16:00:00

In [12]:
len(df)

392976

In [13]:
len(df2)

2076

In [14]:
df2 = df2[(df2['Time_hour'] >= '2012-11-08') & (df2['Time_hour'] < '2012-11-11')]

In [15]:
df2["windSpeed"] = np.nan

In [16]:
df2["Timestamp"] = pd.to_datetime(df2["Time_hour"]).astype('int64')// 10**9

In [17]:
df2.head()

             Time_hour  Rain  Temp  windSpeed   Timestamp
48 2012-11-08 00:00:00   0.0   9.1        NaN  1352332800
49 2012-11-08 01:00:00   0.0   8.9        NaN  1352336400
50 2012-11-08 02:00:00   0.0   8.5        NaN  1352340000
51 2012-11-08 03:00:00   0.0   7.9        NaN  1352343600
52 2012-11-08 04:00:00   0.0   8.2        NaN  1352347200

In [19]:
"""
Put your own api key from darksky when running this loop and remember after 1000 per day they charge you so be careful!
darksky has a dashboard that shows you how many api calls you made
"""
for item,row in df2.iterrows():
    
    dublin = forecast('115860eba8f194a9d04b751787f6a2b8',53.349323, -6.260750, time = row[4], units = 'si')
    df2.set_value(item, 'windSpeed', dublin.hourly[1].windSpeed)

In [20]:
df2.head(50)

             Time_hour  Rain  Temp  windSpeed   Timestamp
48 2012-11-08 00:00:00   0.0   9.1       7.86  1352332800
49 2012-11-08 01:00:00   0.0   8.9       7.86  1352336400
50 2012-11-08 02:00:00   0.0   8.5       7.86  1352340000
51 2012-11-08 03:00:00   0.0   7.9       7.86  1352343600
52 2012-11-08 04:00:00   0.0   8.2       7.86  1352347200
53 2012-11-08 05:00:00   0.0   7.9       7.86  1352350800
54 2012-11-08 06:00:00   0.0   7.6       7.86  1352354400
55 2012-11-08 07:00:00   0.0   7.1       7.86  1352358000
56 2012-11-08 08:00:00   0.0   7.5       7.86  1352361600
57 2012-11-08 09:00:00   0.0   7.5       7.86  1352365200
58 2012-11-08 10:00:00   0.0   8.9       7.86  1352368800
59 2012-11-08 11:00:00   0.0  10.2       7.86  1352372400
60 2012-11-08 12:00:00   0.0  10.8       7.86  1352376000
61 2012-11-08 13:00:00   0.0  10.5       7.86  1352379600
62 2012-11-08 14:00:00   0.0  10.7       7.86  1352383200
63 2012-11-08 15:00:00   0.0  10.4       7.86  1352386800
64 2012-11-08 16:00:00   0.0   9.9       7.86  1352390400
65 2012-11-08 17:00:00   0.0   8.7       7.86  1352394000
66 2012-11-08 18:00:00   0.0   8.8       7.86  1352397600
67 2012-11-08 19:00:00   0.0   7.9       7.86  1352401200
68 2012-11-08 20:00:00   0.0   8.5       7.86  1352404800
69 2012-11-08 21:00:00   0.0   7.8       7.86  1352408400
70 2012-11-08 22:00:00   0.0   7.9       7.86  1352412000
71 2012-11-08 23:00:00   0.0   7.8       7.86  1352415600
72 2012-11-09 00:00:00   0.0   8.3       7.05  1352419200
73 2012-11-09 01:00:00   0.0   8.3       7.05  1352422800
74 2012-11-09 02:00:00   0.0   8.8       7.05  1352426400
75 2012-11-09 03:00:00   0.0   8.7       7.05  1352430000
76 2012-11-09 04:00:00   0.1   8.5       7.05  1352433600
77 2012-11-09 05:00:00   0.7   8.3       7.05  1352437200
78 2012-11-09 06:00:00   0.9   8.4       7.05  1352440800
79 2012-11-09 07:00:00   1.0   8.5       7.05  1352444400
80 2012-11-09 08:00:00   0.4   8.9       7.05  1352448000
81 2012-11-09 09:00:00   0.6   9.3       7.05  1352451600
82 2012-11-09 10:00:00   0.1   9.7       7.05  1352455200
83 2012-11-09 11:00:00   0.8   8.6       7.05  1352458800
84 2012-11-09 12:00:00   0.5   8.5       7.05  1352462400
85 2012-11-09 13:00:00   0.0   8.8       7.05  1352466000
86 2012-11-09 14:00:00   0.0   9.3       7.05  1352469600
87 2012-11-09 15:00:00   0.0   8.7       7.05  1352473200
88 2012-11-09 16:00:00   0.0   8.6       7.05  1352476800
89 2012-11-09 17:00:00   0.0   8.1       7.05  1352480400
90 2012-11-09 18:00:00   0.0   7.2       7.05  1352484000
91 2012-11-09 19:00:00   0.0   6.9       7.05  1352487600
92 2012-11-09 20:00:00   0.0   6.4       7.05  1352491200
93 2012-11-09 21:00:00   0.0   5.6       7.05  1352494800
94 2012-11-09 22:00:00   0.0   6.0       7.05  1352498400
95 2012-11-09 23:00:00   0.0   5.6       7.05  1352502000
96 2012-11-10 00:00:00   0.0   4.9       5.32  1352505600
97 2012-11-10 01:00:00   0.0   4.8       5.32  1352509200

In [21]:
df3 = pd.merge(df,df2, how='inner', on='Time_hour')

In [22]:
len(df3)

392976

In [23]:
len(df)

392976

In [27]:
df3.isnull().sum()

Timestamp_x          0
LineId              16
JourneyPatternId    84
TimeFrame            0
VehicleJourneyId     0
BusOperator          0
Congestion           0
Long                 0
Lat                  0
Delay                0
BlockId              0
VehicleId            0
StopId               0
Distance             0
TravelTime           0
Weekday              0
TimeCategory         0
Time_hour            0
Rain                 0
Temp                 0
windSpeed            0
Timestamp_y          0
dtype: int64

In [31]:
df3 = df3.dropna(axis=0)

,Timestamp_x,LineId,JourneyPatternId,TimeFrame,VehicleJourneyId,BusOperator,Congestion,Long,Lat,Delay,...,StopId,Distance,TravelTime,Weekday,TimeCategory,Time_hour,Rain,Temp,windSpeed,Timestamp_y
0,2012-11-08 16:18:13,331,033A1002,2012-11-08,1,SL,0,-6.129196,53.579613,43,...,3816,0.000000,0,3,16:00,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
1,2012-11-08 16:21:34,331,033A1002,2012-11-08,1,SL,0,-6.110108,53.579807,164,...,3818,1651.209589,201,3,16:00,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
2,2012-11-08 16:24:14,331,033A1002,2012-11-08,1,SL,0,-6.106793,53.580036,309,...,3819,1969.281027,361,3,16:00,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
3,2012-11-08 16:33:52,331,033A1002,2012-11-08,1,SL,0,-6.090593,53.533672,623,...,3833,7472.199689,939,3,16:30,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
4,2012-11-08 16:34:33,331,033A1002,2012-11-08,1,SL,0,-6.091514,53.530941,648,...,3834,7783.316730,980,3,16:30,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
5,2012-11-08 16:35:32,331,033A1002,2012-11-08,1,SL,0,-6.091316,53.528820,697,...,3835,8019.765742,1039,3,16:30,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
6,2012-11-08 16:37:13,331,033A1002,2012-11-08,1,SL,0,-6.091219,53.523346,767,...,3836,8629.680007,1140,3,16:30,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
7,2012-11-08 16:40:53,331,033A1002,2012-11-08,1,SL,0,-6.100092,53.522839,950,...,3840,9357.375105,1360,3,16:30,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
8,2012-11-08 16:42:13,331,033A1002,2012-11-08,1,SL,0,-6.105506,53.521587,996,...,3842,9742.671636,1440,3,16:30,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
9,2012-11-08 16:49:03,331,033A1002,2012-11-08,1,SL,0,-6.164808,53.525356,1021,...,3854,13918.041321,1850,3,16:30,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
10,2012-11-08 16:50:43,331,033A1002,2012-11-08,1,SL,0,-6.167720,53.523067,1061,...,3855,14255.122540,1950,3,16:30,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
11,2012-11-08 16:54:03,331,033A1002,2012-11-08,1,SL,0,-6.185406,53.507065,893,...,3860,16450.819038,2150,3,16:30,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
12,2012-11-08 16:04:04,41,041C1001,2012-11-08,19,SL,0,-6.251184,53.459583,0,...,4843,0.000000,0,3,16:00,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
13,2012-11-08 16:05:26,41,041C1001,2012-11-08,19,SL,0,-6.245201,53.459927,-44,...,4905,399.579242,82,3,16:00,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
14,2012-11-08 16:07:04,41,041C1001,2012-11-08,19,SL,0,-6.239713,53.465740,-120,...,4909,1333.622385,180,3,16:00,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
15,2012-11-08 16:09:03,41,041C1001,2012-11-08,19,SL,0,-6.230776,53.469257,-182,...,4922,2241.021255,299,3,16:00,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
16,2012-11-08 16:09:42,41,041C1001,2012-11-08,19,SL,0,-6.227864,53.468571,-182,...,4923,2448.926219,338,3,16:00,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
17,2012-11-08 16:15:02,41,041C1001,2012-11-08,19,SL,0,-6.220045,53.458977,-298,...,3689,4136.169078,658,3,16:00,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
18,2012-11-08 16:17:17,41,041C1001,2012-11-08,19,SL,0,-6.221763,53.456001,-258,...,3691,4486.604195,793,3,16:00,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
19,2012-11-08 16:20:34,41,041C1001,2012-11-08,19,SL,0,-6.232339,53.452003,-300,...,3702,5381.851446,990,3,16:00,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
20,2012-11-08 16:21:15,41,041C1001,2012-11-08,19,SL,0,-6.237076,53.452766,-347,...,3088,5711.143052,1031,3,16:00,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
21,2012-11-08 16:22:15,41,041C1001,2012-11-08,19,SL,0,-6.244240,53.452793,-368,...,3705,6271.173447,1091,3,16:00,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
22,2012-11-08 16:23:35,41,041C1001,2012-11-08,19,SL,0,-6.240490,53.449360,-390,...,733,6859.923165,1171,3,16:00,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
23,2012-11-08 16:24:55,41,041C1001,2012-11-08,19,SL,0,-6.235275,53.445465,-373,...,5029,7417.958411,1251,3,16:00,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
24,2012-11-08 16:27:14,41,041C1001,2012-11-08,19,SL,0,-6.227999,53.435146,-526,...,3699,8933.970822,1390,3,16:00,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
25,2012-11-08 16:34:45,41,041C1001,2012-11-08,19,SL,0,-6.237739,53.408180,-860,...,1636,12196.020715,1841,3,16:30,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
26,2012-11-08 16:38:46,41,041C1001,2012-11-08,19,SL,0,-6.245244,53.396519,-801,...,1639,13596.308163,2082,3,16:30,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
27,2012-11-08 16:40:06,41,041C1001,2012-11-08,19,SL,0,-6.246103,53.392368,-897,...,1640,14061.809730,2162,3,16:30,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
28,2012-11-08 16:42:44,41,041C1001,2012-11-08,19,SL,0,-6.242439,53.386570,-977,...,1641,14861.662385,2320,3,16:30,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
29,2012-11-08 16:43:23,41,041C1001,2012-11-08,19,SL,0,-6.243611,53.384007,-977,...,1642,15157.605038,2359,3,16:30,2012-11-08 16:00:00,0.0,9.9,7.86,1352390400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392945,2012-11-10 21:27:43,83,083A1001,2012-11-10,13311,HN,0,-6.292329,53.389877,-142,...,138,15042.917117,3479,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392946,2012-11-10 21:28:42,83,083A1001,2012-11-10,13311,HN,0,-6.286194,53.390797,-142,...,133,15492.379700,3538,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392947,2012-11-10 21:29:43,83,083A1001,2012-11-10,13311,HN,0,-6.286043,53.393143,-111,...,134,15769.512787,3599,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392948,2012-11-10 21:32:43,83,083A1001,2012-11-10,13311,HN,0,-6.298603,53.402054,-121,...,6229,17290.311364,3779,5,21:30,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392949,2012-11-10 21:43:24,83,083A1001,2012-11-10,13311,HN,0,-6.279433,53.416965,-40,...,332,23383.554772,4420,5,21:30,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392950,2012-11-10 21:45:24,83,00830001,2012-11-10,13312,HN,0,-6.274892,53.417973,0,...,7477,0.000000,0,5,21:30,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392951,2012-11-10 21:49:44,83,00830001,2012-11-10,13312,HN,0,-6.306915,53.418274,-25,...,1555,4042.709772,260,5,21:30,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392952,2012-11-10 21:56:25,83,00830001,2012-11-10,13312,HN,0,-6.286919,53.393143,-107,...,4891,7708.589245,661,5,21:30,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392953,2012-11-10 21:58:03,83,00830001,2012-11-10,13312,HN,0,-6.290523,53.390072,-67,...,7458,8187.947025,759,5,21:30,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392954,2012-11-10 21:04:05,4,00041001,2012-11-10,903582,HN,0,-6.273111,53.358894,1512,...,197,1521.182024,359,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392955,2012-11-10 21:05:26,4,00041001,2012-11-10,903582,HN,0,-6.272702,53.361622,1512,...,198,1827.619366,440,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392956,2012-11-10 21:06:07,4,00041001,2012-11-10,903582,HN,0,-6.272180,53.363560,1530,...,199,2047.832761,481,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392957,2012-11-10 21:08:27,4,00041001,2012-11-10,903582,HN,0,-6.271604,53.367348,1577,...,200,2552.737142,621,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392958,2012-11-10 21:10:07,4,00041001,2012-11-10,903582,HN,0,-6.268030,53.370617,1577,...,148,3022.493789,721,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392959,2012-11-10 21:12:46,4,00041001,2012-11-10,903582,HN,0,-6.266495,53.379368,1631,...,27,4095.983081,880,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392960,2012-11-10 21:14:04,4,00041001,2012-11-10,903582,HN,0,-6.265242,53.384956,1631,...,4680,4724.357897,958,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392961,2012-11-10 21:15:05,4,00041001,2012-11-10,903582,HN,0,-6.265268,53.388367,1651,...,91,5104.535225,1019,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392962,2012-11-10 21:16:25,4,00041001,2012-11-10,903582,HN,0,-6.264594,53.389801,1704,...,92,5270.311088,1099,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392963,2012-11-10 21:18:05,4,00041001,2012-11-10,903582,HN,0,-6.264242,53.396027,1704,...,94,5967.258684,1199,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392964,2012-11-10 21:19:07,4,00041001,2012-11-10,903582,HN,0,-6.263979,53.399078,1732,...,126,6307.310137,1261,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392965,2012-11-10 21:21:06,4,00041001,2012-11-10,903582,HN,0,-6.265346,53.404251,1769,...,322,6896.246093,1380,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392966,2012-11-10 21:24:06,4,00041001,2012-11-10,915744,HN,0,-6.266495,53.379368,500,...,27,0.000000,0,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392967,2012-11-10 21:25:07,4,00041001,2012-11-10,915744,HN,0,-6.265862,53.381565,544,...,28,250.407975,61,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392968,2012-11-10 21:26:06,4,00041001,2012-11-10,915744,HN,0,-6.265242,53.384956,562,...,4680,630.171400,120,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392969,2012-11-10 21:26:45,4,00041001,2012-11-10,915744,HN,0,-6.265181,53.386395,584,...,90,790.524072,159,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392970,2012-11-10 21:27:27,4,00041001,2012-11-10,915744,HN,0,-6.265268,53.388367,584,...,91,1010.349463,201,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392971,2012-11-10 21:28:05,4,00041001,2012-11-10,915744,HN,0,-6.264594,53.389801,607,...,92,1176.125406,239,5,21:00,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392972,2012-11-10 21:30:06,4,00041001,2012-11-10,915744,HN,0,-6.264242,53.396027,639,...,94,1872.365932,360,5,21:30,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392973,2012-11-10 21:32:27,4,00041001,2012-11-10,915744,HN,0,-6.265352,53.402248,672,...,6182,2580.336786,501,5,21:30,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200
392974,2012-11-10 21:33:06,4,00041001,2012-11-10,915744,HN,0,-6.265346,53.404251,691,...,322,2803.258720,540,5,21:30,2012-11-10 21:00:00,0.0,3.6,5.32,1352581200

In [32]:
df3.isnull().sum()

Timestamp_x          0
LineId              16
JourneyPatternId    84
TimeFrame            0
VehicleJourneyId     0
BusOperator          0
Congestion           0
Long                 0
Lat                  0
Delay                0
BlockId              0
VehicleId            0
StopId               0
Distance             0
TravelTime           0
Weekday              0
TimeCategory         0
Time_hour            0
Rain                 0
Temp                 0
windSpeed            0
Timestamp_y          0
dtype: int64